#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/velhos

###

POST http://localhost:3333/velhos
Content-Type: application/json

{
    "nome": "Sandro",
    "nascimento": "1955-08-01",
    "telefone": "9999-9999",
    "fotoperfil": "a",
    "biografia": "legal"
}

###

PUT http://localhost:3333/velhos/40205649-aefe-4479-abcf-cad436940b63
Content-Type: application/json

{
    "nome": "Jaime",
    "nascimento": "1959-08-01",
    "telefone": "9999-9999",
    "fotoperfil": "a",
    "biografia": "legal"
}

###

DELETE http://localhost:3333/velhos/40205649-aefe-4479-abcf-cad436940b63
